### ISSUE TITLE
課題提出について

### ISSUE THREAD

**Issue by yuu030** [integrated-design/2015-db2-web#23]
提出は、提出フォルダの07_websiteでいいですか？

掲示には課題フォルダと書いてあったのですが。

**Comment by hgw** [comment]
おや、お知らせありがとうございますー。
混乱させてしまってすいません。
提出フォルダに提出をお願いします。

一応課題フォルダに入っているものも確認するようにします。

**Comment by hgw** [comment]
こっちも閉じますー。
