### ISSUE TITLE
再提出について

### ISSUE THREAD

**Issue by yuu030** [integrated-design/2015-db2-web#25]
期限はいつまででしょうか？

提出先は、前回と同様で、修正したものを同じように入れてあれば大丈夫ですか？

**Comment by hgw** [comment]
@yuu030 

あ、期限を掲載していませんでしたね。すみませんー。
内容のチェックに時間がかかってしまったので、来週25日(水) 13:00 までにしましょう。再掲します :memo: 

フォルダは前回と同じもので大丈夫です。
