### ISSUE TITLE
WEBの再提出について

### ISSUE THREAD

**Issue by rn5** [integrated-design/2015-db2-web#26]
@hgw お世話になっております、Bクラスの志田です。
WEBの再提出の件についてなのですが、水曜日に学校を休んでしまい、提出フォルダに提出をすることが出来ませんでした。申し訳ありません…
ご連絡が遅くなってしまい大変恐縮なのですが、その後の修正したデータの提出は、自分でhetemlにアップロードする形で大丈夫でしょうか？それとも次の水曜までに提出フォルダに提出しておく形が良いでしょうか？

（ちなみに私の問題は、一部画像ファイルに数十MBのpngファイルがあったというもので、10MBを超えていたものに関しては全て10MB以下のpngファイル（解像度を下げました）に修正済みです。）

お手数おかけして大変申し訳ないのですが、お答えいただければ幸いです。宜しくお願い致します。

**Comment by hgw** [comment]
@rn5 

ご連絡ありがとう！課題は **提出フォルダ** へ提出をお願いします。水曜日に回収するので、2日のお昼までに提出しておいてください。こちらで確認後、問題なければ heteml へアップします。

:memo: 
その他のひとの修正分については、今チェックしているので再アップしたらまた掲示します。
