### ISSUE TITLE
タイトル横にメニューを配置したい

### ISSUE THREAD

**Issue by ghost** [integrated-design/2015-db2-web#27]
h1タグで囲ったタイトルのすぐ右隣にメニュー部を配置したいのですが、メニュー部が自動的に改行されてしまいます。どうしたらよいでしょうか。

**Comment by hgw** [comment]
@ramuzo 

> h1タグで囲ったタイトルのすぐ右隣にメニュー部を配置したい

ということで、 css の `float` をつかってみてはどうでしょう？以下にサンプルがあります。

![image](https://cloud.githubusercontent.com/assets/333662/12229446/1654066e-b88b-11e5-94db-5cff49c8ccfb.png)

http://codepen.io/hgw/pen/qbjbYo

---

もしわからなかったら HTML と CSS のコードをコメントに貼ってみてもらえますか？
やり方はいくつかあるので、実際のコードを見たほうが回答しやすいです。

検索だと「 [float レイアウト](https://www.google.co.jp/search?q=float+%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88&oq=float+%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88&aqs=chrome..69i57j69i60j69i61.383j0j1&sourceid=chrome&es_sm=91&ie=UTF-8) 」 で調べるといろいろ出てくると思います :mag:

**Comment by ghost** [comment]
できました！ありがとうございます！

**Comment by hgw** [comment]
@ramuzo 

良かったでーす。がんばって :+1:
